name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 0.1.3
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  quill_delta: ^1.0.0
  quiver_hashcode: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
